"""Educational models and utilities for Biomechanics Research Tutorials."""

from .active_mechanics import (
    ActivationParameters,
    ActiveTensionParameters,
    CrossbridgeParameters,
    ForceLengthParameters,
    ForceVelocityParameters,
    activation_biexponential,
    active_strain_tensor,
    active_tension,
    force_length,
    force_velocity,
)
from .collagen_dispersion import (
    DispersionParameters,
    FiberMaterialParameters,
    axial_von_mises_density,
    nominal_stress,
    orientation_tensor,
)
from .fiber_reorientation import (
    ReorientationParameters,
    angular_difference,
    simulate_reorientation,
)
from .mechanical_homeostasis import (
    ConstituentTurnoverParameters,
    HomeostasisParameters,
    VesselHomeostasisParameters,
    analytical_capacity_response,
    feedback_response,
    generate_load_protocol,
    homeostasis_metrics,
    simulate_constituent_turnover,
    simulate_scalar_homeostasis,
    simulate_vessel_homeostasis,
    survival_fraction,
    vessel_equilibrium,
    vessel_stimuli,
)
from .structure_tensor import (
    StructureTensorParameters,
    axial_angle_difference as structure_tensor_axial_difference,
    structure_tensor_orientation,
    synthetic_parallel_fibers,
)
from .growth_kinematics import (
    GrowthLawParameters,
    GrowthMaterialParameters,
    growth_tensor_isotropic,
    growth_tensor_orthotropic,
    growth_tensor_transversely_isotropic,
    incompatibility_norm_2d,
    multiplicative_decomposition,
    reduced_strip_equilibrium,
    simulate_stress_driven_growth,
    total_first_piola,
    total_reference_energy,
)
from .hyperelasticity import (
    MODEL_DEFINITIONS,
    deformation_gradient,
    model_catalog,
    path_response,
    strain_energy,
)

# Tutorial 08: stress-driven volumetric growth
from .volumetric_growth import (
    VolumetricGrowthLawParameters,
    density_ratio_from_mass,
    evaluate_growth_stimulus,
    growth_response,
    homeostatic_band_value,
    isotropic_growth_tensor,
    linearized_log_growth_eigenvalue,
    mass_ratio_from_growth,
    simulate_prescribed_deformation,
    simulate_prescribed_mean_stress,
    simulate_spatial_growth_field,
    stress_invariants,
    update_volume_ratio_exponential,
)

# Tutorial 09: fiber-family remodeling
from .fiber_family_remodeling import (
    Cohort,
    FiberFamily,
    FiberMaterialParameters as RemodelingFiberMaterialParameters,
    ODFRemodelingParameters,
    RecruitmentParameters,
    ReorientationParameters as FamilyReorientationParameters,
    TurnoverParameters,
    angular_integrated_energy,
    axial_mean_angle,
    axial_order_parameter,
    compare_approach_state_count,
    planar_structure_tensor_energy,
    recruitment_tension,
    simulate_cohort_turnover,
    simulate_discrete_reorientation,
    simulate_odf_remodeling,
    simulate_two_family_mass_remodeling,
)

# Tutorial 10: extracellular-matrix turnover
from .ecm_turnover import (
    Cohort as ECMCohort,
    CollagenKineticsParameters,
    MatrixComponent,
    MechanobiologyParameters,
    SurvivalParameters,
    collagen_fiber_tension,
    compare_model_state_count,
    effective_collagen_stiffness,
    matrix_nominal_stress,
    mmp_timp_activity,
    simulate_cohort_turnover as simulate_ecm_cohort_turnover,
    simulate_collagen_maturation,
    simulate_homogenized_turnover,
    simulate_multicomponent_ecm,
    simulate_spatial_degradation,
    survival_fraction as ecm_survival_fraction,
    turnover_metrics,
)

# Tutorial 12: residual stress and ring opening
from .residual_stress import (
    SectorLayer,
    TubeSolution,
    closure_factor,
    curvature_to_opening_angle,
    equilibrated_strip,
    inverse_loss_surface,
    monte_carlo_opening_angle,
    multi_sector_angles,
    opening_sector_coordinates,
    pressure_for_inner_radius,
    radial_boundary_residual,
    ring_coordinates,
    solve_inner_radius,
    solve_sector_tube,
    stress_gradient,
    stress_uniformity,
)

# Tutorial 11: constrained-mixture toy model
from .constrained_mixture import (
    CohortRecord as MixtureCohortRecord,
    ConstituentParameters as MixtureConstituentParameters,
    MixtureSimulationParameters,
    cardiac_loading_protocol,
    initialize_cardiac_constituents,
    initialize_homeostatic_targets as initialize_mixture_homeostasis,
    mixture_mass_fractions,
    mixture_metrics,
    model_state_count as constrained_mixture_state_count,
    polarimetry_to_mixture_prior,
    simulate_constrained_mixture,
    simulate_homogenized_mixture,
)

__all__ = [
    "SectorLayer",
    "TubeSolution",
    "closure_factor",
    "curvature_to_opening_angle",
    "equilibrated_strip",
    "inverse_loss_surface",
    "monte_carlo_opening_angle",
    "multi_sector_angles",
    "opening_sector_coordinates",
    "pressure_for_inner_radius",
    "radial_boundary_residual",
    "ring_coordinates",
    "solve_inner_radius",
    "solve_sector_tube",
    "stress_gradient",
    "stress_uniformity",
    "MixtureCohortRecord",
    "MixtureConstituentParameters",
    "MixtureSimulationParameters",
    "cardiac_loading_protocol",
    "initialize_cardiac_constituents",
    "initialize_mixture_homeostasis",
    "mixture_mass_fractions",
    "mixture_metrics",
    "constrained_mixture_state_count",
    "polarimetry_to_mixture_prior",
    "simulate_constrained_mixture",
    "simulate_homogenized_mixture",
    "ECMCohort",
    "CollagenKineticsParameters",
    "MatrixComponent",
    "MechanobiologyParameters",
    "SurvivalParameters",
    "collagen_fiber_tension",
    "compare_model_state_count",
    "effective_collagen_stiffness",
    "matrix_nominal_stress",
    "mmp_timp_activity",
    "simulate_ecm_cohort_turnover",
    "simulate_collagen_maturation",
    "simulate_homogenized_turnover",
    "simulate_multicomponent_ecm",
    "simulate_spatial_degradation",
    "ecm_survival_fraction",
    "turnover_metrics",
    "total_reference_energy",
    "total_first_piola",
    "simulate_stress_driven_growth",
    "reduced_strip_equilibrium",
    "multiplicative_decomposition",
    "incompatibility_norm_2d",
    "growth_tensor_transversely_isotropic",
    "growth_tensor_orthotropic",
    "growth_tensor_isotropic",
    "GrowthMaterialParameters",
    "GrowthLawParameters",
    "vessel_stimuli",
    "vessel_equilibrium",
    "survival_fraction",
    "simulate_vessel_homeostasis",
    "simulate_scalar_homeostasis",
    "simulate_constituent_turnover",
    "homeostasis_metrics",
    "generate_load_protocol",
    "feedback_response",
    "analytical_capacity_response",
    "VesselHomeostasisParameters",
    "HomeostasisParameters",
    "ConstituentTurnoverParameters",
    "ActivationParameters",
    "ActiveTensionParameters",
    "CrossbridgeParameters",
    "ForceLengthParameters",
    "ForceVelocityParameters",
    "activation_biexponential",
    "active_strain_tensor",
    "active_tension",
    "force_length",
    "force_velocity",
    "DispersionParameters",
    "FiberMaterialParameters",
    "MODEL_DEFINITIONS",
    "ReorientationParameters",
    "angular_difference",
    "axial_von_mises_density",
    "deformation_gradient",
    "model_catalog",
    "nominal_stress",
    "orientation_tensor",
    "path_response",
    "simulate_reorientation",
    "strain_energy",
    "StructureTensorParameters",
    "structure_tensor_axial_difference",
    "structure_tensor_orientation",
    "synthetic_parallel_fibers",
    "VolumetricGrowthLawParameters",
    "density_ratio_from_mass",
    "evaluate_growth_stimulus",
    "growth_response",
    "homeostatic_band_value",
    "isotropic_growth_tensor",
    "linearized_log_growth_eigenvalue",
    "mass_ratio_from_growth",
    "simulate_prescribed_deformation",
    "simulate_prescribed_mean_stress",
    "simulate_spatial_growth_field",
    "stress_invariants",
    "update_volume_ratio_exponential",
    "Cohort",
    "FamilyReorientationParameters",
    "FiberFamily",
    "ODFRemodelingParameters",
    "RecruitmentParameters",
    "RemodelingFiberMaterialParameters",
    "TurnoverParameters",
    "angular_integrated_energy",
    "axial_mean_angle",
    "axial_order_parameter",
    "compare_approach_state_count",
    "planar_structure_tensor_energy",
    "recruitment_tension",
    "simulate_cohort_turnover",
    "simulate_discrete_reorientation",
    "simulate_odf_remodeling",
    "simulate_two_family_mass_remodeling",
]

from .constrained_mixture import generic_fibrous_constituents as generic_fibrous_constituents

from .constrained_mixture import initialize_generic_constituents as initialize_generic_constituents

from .constrained_mixture import generic_loading_protocol as generic_loading_protocol

from .constrained_mixture import imaging_to_mixture_prior as imaging_to_mixture_prior

# Tutorial 13: synthetic fibrous-tissue generation
from .synthetic_fibrous_tissue import (
    Fiber2D,
    FiberNetwork2D,
    FiberVolume3D,
    RasterizedNetwork2D,
    add_branches,
    apply_defects,
    export_network_dataset,
    generate_crossing_families,
    generate_fiber_volume,
    generate_layered_network,
    generate_mikado_network,
    generate_parallel_bundle,
    generate_spatial_gradient_network,
    generate_voronoi_network,
    morphological_skeleton,
    network_metrics,
    rasterize_network,
    skeleton_graph_metrics,
    tissue_preset,
)


__all__ += [
    "Fiber2D",
    "FiberNetwork2D",
    "FiberVolume3D",
    "RasterizedNetwork2D",
    "add_branches",
    "apply_defects",
    "export_network_dataset",
    "generate_crossing_families",
    "generate_fiber_volume",
    "generate_layered_network",
    "generate_mikado_network",
    "generate_parallel_bundle",
    "generate_spatial_gradient_network",
    "generate_voronoi_network",
    "morphological_skeleton",
    "network_metrics",
    "rasterize_network",
    "skeleton_graph_metrics",
    "tissue_preset",
]

# Tutorial 14: synthetic microscopy and SEM-like imaging
from .synthetic_microscopy import (  # noqa: E402
    ArtifactParameters,
    OpticalParameters,
    SEMParameters,
    SyntheticImageResult,
    apply_artifacts,
    export_multimodal_dataset,
    focus_series,
    gaussian_psf_blur,
    global_ssim,
    height_from_mask,
    normalize01,
    poisson_gaussian_noise,
    psnr,
    read_multimodal_metadata,
    resample_stack,
    simulate_brightfield,
    simulate_confocal_stack,
    simulate_fib_sem_stack,
    simulate_fluorescence,
    simulate_sem,
    simulate_shg,
)

__all__ += [
    "ArtifactParameters",
    "OpticalParameters",
    "SEMParameters",
    "SyntheticImageResult",
    "apply_artifacts",
    "export_multimodal_dataset",
    "focus_series",
    "gaussian_psf_blur",
    "global_ssim",
    "height_from_mask",
    "normalize01",
    "poisson_gaussian_noise",
    "psnr",
    "read_multimodal_metadata",
    "resample_stack",
    "simulate_brightfield",
    "simulate_confocal_stack",
    "simulate_fib_sem_stack",
    "simulate_fluorescence",
    "simulate_sem",
    "simulate_shg",
]
# Tutorial 15: polarization-like orientation maps
from .polarization_orientation import (  # noqa: E402
    OrientationRecovery,
    PolarizationParameters,
    PolarizationSeries,
    add_polarization_noise,
    axial_difference as polarization_axial_difference,
    axial_wrap as polarization_axial_wrap,
    calibration_sweep,
    crossed_polarizer_intensity,
    estimate_retardance_from_modulation,
    export_polarization_dataset,
    harmonic_design_matrix,
    jones_linear_retarder,
    multilayer_jones_intensity,
    orientation_error_deg,
    quadrature_orientation_error_deg,
    read_polarization_metadata,
    recover_orientation_harmonic,
    retardance_from_birefringence,
    simulate_polarization_series,
    synthetic_illumination_field,
)

__all__ += [
    "OrientationRecovery",
    "PolarizationParameters",
    "PolarizationSeries",
    "add_polarization_noise",
    "polarization_axial_difference",
    "polarization_axial_wrap",
    "calibration_sweep",
    "crossed_polarizer_intensity",
    "estimate_retardance_from_modulation",
    "export_polarization_dataset",
    "harmonic_design_matrix",
    "jones_linear_retarder",
    "multilayer_jones_intensity",
    "orientation_error_deg",
    "quadrature_orientation_error_deg",
    "read_polarization_metadata",
    "recover_orientation_harmonic",
    "retardance_from_birefringence",
    "simulate_polarization_series",
    "synthetic_illumination_field",
]
# Tutorial 16: synthetic digital image correlation
from .digital_image_correlation import (  # noqa: E402
    DICGridResult,
    DICParameters,
    SpeckleParameters,
    StrainFields,
    correlation_surface,
    dic_metrics,
    displacement_field,
    estimate_subset_displacement,
    export_dic_dataset,
    forward_backward_error,
    generate_natural_texture,
    generate_speckle_pattern,
    interpolate_sparse_field,
    principal_strains_2d,
    quadratic_subpixel_peak,
    read_dic_metadata,
    refine_affine_subset,
    run_subset_dic,
    sample_truth_on_dic_grid,
    strain_fields,
    virtual_extensometer,
    warp_image,
    zncc,
    znssd,
)

__all__ += [
    "DICGridResult",
    "DICParameters",
    "SpeckleParameters",
    "StrainFields",
    "correlation_surface",
    "dic_metrics",
    "displacement_field",
    "estimate_subset_displacement",
    "export_dic_dataset",
    "forward_backward_error",
    "generate_natural_texture",
    "generate_speckle_pattern",
    "interpolate_sparse_field",
    "principal_strains_2d",
    "quadratic_subpixel_peak",
    "read_dic_metadata",
    "refine_affine_subset",
    "run_subset_dic",
    "sample_truth_on_dic_grid",
    "strain_fields",
    "virtual_extensometer",
    "warp_image",
    "zncc",
    "znssd",
]


# Tutorial 20: multimodal verification-ready synthetic benchmark
from .multimodal_benchmark import (  # noqa: E402
    GroundTruthMicrostructure, SyntheticModalities, LoadCase as MultimodalLoadCase,
    PipelineResult, axial_difference as multimodal_axial_difference, binary_metrics,
    build_load_cases, estimate_parameters, generate_ground_truth_microstructure,
    render_modalities, run_full_benchmark, segment_modalities,
)

__all__ += [
    "GroundTruthMicrostructure", "SyntheticModalities", "MultimodalLoadCase",
    "PipelineResult", "multimodal_axial_difference", "binary_metrics",
    "build_load_cases", "estimate_parameters", "generate_ground_truth_microstructure",
    "render_modalities", "run_full_benchmark", "segment_modalities",
]

# Tutorial 21 module: finite_element_growth

# Tutorial 22: RVE homogenization
from .rve_homogenization import (  # noqa: E402
    HomogenizationResult,
    LocalMaterialParameters,
    Microstructure,
    PeriodicCaseResult,
    RVEMesh,
    affine_displacement,
    convergence_study,
    create_periodic_tri_mesh,
    directional_young_modulus,
    export_rve_dataset,
    fiber_reinforced_stiffness,
    generate_microstructure,
    homogenize_rve,
    local_stiffness_for_mesh,
    periodic_reduction_matrix,
    plane_stress_isotropic,
    reuss_bound,
    solve_periodic_case,
    stiffness_summary,
    voigt_bound,
)

__all__ += [
    "HomogenizationResult",
    "LocalMaterialParameters",
    "Microstructure",
    "PeriodicCaseResult",
    "RVEMesh",
    "affine_displacement",
    "convergence_study",
    "create_periodic_tri_mesh",
    "directional_young_modulus",
    "export_rve_dataset",
    "fiber_reinforced_stiffness",
    "generate_microstructure",
    "homogenize_rve",
    "local_stiffness_for_mesh",
    "periodic_reduction_matrix",
    "plane_stress_isotropic",
    "reuss_bound",
    "solve_periodic_case",
    "stiffness_summary",
    "voigt_bound",
]

# Tutorial 25: sensitivity analysis and uncertainty quantification
from .sensitivity_uncertainty import (  # noqa: E402
    PARAMETERS, OUTPUT_NAMES, ParameterSpec, convergence_trace, evaluate_tissue_model,
    latin_hypercube, likelihood_update, monte_carlo, morris_screening, nominal_parameter_vector,
    parameter_table, parameters_to_unit_cube, posterior_summary, reliability_metrics,
    run_full_uq, sample_parameters, sobol_pick_freeze, summarize_outputs, tornado_analysis,
    unit_cube_to_parameters, weighted_quantile,
)

__all__ += [
    "PARAMETERS", "OUTPUT_NAMES", "ParameterSpec", "convergence_trace",
    "evaluate_tissue_model", "latin_hypercube", "likelihood_update", "monte_carlo",
    "morris_screening", "nominal_parameter_vector", "parameter_table",
    "parameters_to_unit_cube", "posterior_summary", "reliability_metrics",
    "run_full_uq", "sample_parameters", "sobol_pick_freeze", "summarize_outputs",
    "tornado_analysis", "unit_cube_to_parameters", "weighted_quantile",
]
